version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PUBLIC_BACKEND_URL: https://pay.animussociety.com
        PUBLIC_OPPWA_URL: https://eu-prod.oppwa.com
    container_name: animus-society-frontend
    ports:
      - "4321:4321"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=4321
      - PUBLIC_BACKEND_URL=https://pay.animussociety.com
      - PUBLIC_OPPWA_URL=https://eu-prod.oppwa.com
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4321"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s